package_assets:         on      

embed_assets:           off         
compress_assets:        on          
gzip_assets:            on          
javascript_compressor:  closure  
compressor_options:
#	compilation_level: "ADVANCED_OPTIMIZATIONS"

javascripts:

  rackjam:
    - public/javascripts/jquery.min.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/isotope/jquery.isotope.min.js
    - public/javascripts/jquery.hoverintent.minified.js
    - public/javascripts/jcarousellite_1.0.1.pack.js
    - public/javascripts/jquery.easing.1.3.js
    - public/javascripts/jquery-ui-1.8.16.custom.min.js
    - public/javascripts/jquery.ui.selectmenu.js
    - public/javascripts/cookies.jquery.js    
    - public/javascripts/application.js

stylesheets:
  rackjam:
    - public/stylesheets/main.css
    - public/stylesheets/jquery-ui-1.8.16.custom.css
