package_assets:         on      
embed_assets:           off         
compress_assets:        on          
gzip_assets:            on          
javascript_compressor:  closure  
compressor_options:
#	compilation_level: "ADVANCED_OPTIMIZATIONS"

javascripts:

  rackjam:
    - public/javascripts/jquery.min.js
    - public/javascripts/cookies.jquery.js
    - public/javascripts/jquery_ujs.js
    - public/javascripts/isotope/jquery.isotope.min.js
    - public/javascripts/application.js

stylesheets:
  rackjam:
    - public/stylesheets/main.css